Object.defineProperty(exports, "__esModule", {
  value: true
});
var FETCHING = exports.FETCHING = "FETCHING";
var GET_PORTFOLIO = exports.GET_PORTFOLIO = "GET_MY_PORTFOLIO";
var GET_PORTFOLIO_FULFILLED = exports.GET_PORTFOLIO_FULFILLED = "GET_PORTFOLIO_FULFILLED";
var GET_PORTFOLIO_ERROR = exports.GET_PORTFOLIO_ERROR = "GET_PORTFOLIO_ERROR";
var SHOWCASE_SEARCHVALUE_CHANGED = exports.SHOWCASE_SEARCHVALUE_CHANGED = "SHOWCASE_SEARCHVALUE_CHANGED";
var SHOWCASE_SEARCHVALUE_CLEAR = exports.SHOWCASE_SEARCHVALUE_CLEAR = "SHOWCASE_SEARCHVALUE_CLEAR";

var GET_TAG_AUTOCOMPLETE = exports.GET_TAG_AUTOCOMPLETE = "GET_TAG_AUTOCOMPLETE";
var GET_TAG_AUTOCOMPLETE_FULFILLED = exports.GET_TAG_AUTOCOMPLETE_FULFILLED = "GET_TAG_AUTOCOMPLETE_FULFILLED";
var GET_SHOWCASE_SUGGESTED_TAGS = exports.GET_SHOWCASE_SUGGESTED_TAGS = "GET_SHOWCASE_SUGGESTED_TAGS";
var GET_SHOWCASE_SUGGESTED_TAGS_FULFILLED = exports.GET_SHOWCASE_SUGGESTED_TAGS_FULFILLED = "GET_SHOWCASE_SUGGESTED_TAGS_FULFILLED";

var SET_TAG_AUTOCOMPLETE = exports.SET_TAG_AUTOCOMPLETE = "SET_TAG_AUTOCOMPLETE";
var SET_TAG_AUTOCOMPLETE_FULFILLED = exports.SET_TAG_AUTOCOMPLETE_FULFILLED = "SET_TAG_AUTOCOMPLETE_FULFILLED";