Object.defineProperty(exports,"__esModule",{value:true});var FETCHING=exports.FETCHING="FETCHING";
var PROJECT_TYPE_CHANGED=exports.PROJECT_TYPE_CHANGED="PROJECT_TYPE_CHANGED";
var GET_MY_BOOKMARK=exports.GET_MY_BOOKMARK="GET_MY_BOOKMARK";
var GET_MY_BOOKMARK_FULFILLED=exports.GET_MY_BOOKMARK_FULFILLED="GET_MY_BOOKMARK_FULFILLED";
var GET_MY_BOOKMARK_ERROR=exports.GET_MY_BOOKMARK_ERROR="GET_MY_BOOKMARK_ERROR";