export const FETCHING = "FETCHING"

export const GET_PROJECTS_WITH_SKILLS = "GET_PROJECTS_WITH_SKILLS"
export const GET_PROJECTS_WITH_SKILLS_FAILED = "GET_PROJECTS_WITH_SKILLS_FAILED"
export const GET_PROJECTS_WITH_SKILLS_FULFILLED = "GET_PROJECTS_WITH_SKILLS_FULFILLED"

//NEW PROJECTS
export const NEW_PROJECT = "NEW_PROJECT"

export const GET_TAGS = "GET_TAGS"
export const GET_TAGS_FULFILLED = "GET_TAGS_FULFILLED"
export const GET_TAGS_FAILED = "GET_TAGS_FAILED"

export const TAG_SELECTED = "TAG_SELECTED"
export const TAG_DISELECT = "TAG_DISELECT"
export const TAG_REMOVE = "TAG_REMOVE"

//2. Wizard
export const GET_SUGGESTED_SHOWCASES = "GET_SUGGESTED_SHOWCASES"
export const GET_SUGGESTED_SHOWCASES_FULFILLED = "GET_SUGGESTED_SHOWCASES_FULFILLED"

//SELECTED
export const SUGGESTED_IMAGE_CHOOSED = "SUGGESTED_IMAGE_CHOOSED"

export const GET_SKILL_CATEGORIES = "GET_SKILL_CATEGORIES"
export const GET_SKILL_CATEGORIES_FAILED = "GET_SKILL_CATEGORIES_FAILED"
export const GET_SKILL_CATEGORIES_FULFILLED = "GET_SKILL_CATEGORIES_FULFILLED"

export const SET_SELECTED_PROJECT = "SET_SELECTED_PROJECT"

export const SAVE_PROJECT = 'SAVE_PROJECT'
export const SAVE_PROJECT_FAILED = 'SAVE_PROJECT_FAILED'
export const SAVE_PROJECT_FULFILLED = 'SAVE_PROJECT_FULFILLED'

export const PRICE_BUNDLE_CHANGED = "PRICE_BUNDLE_CHANGED"
export const DURATION_TYPE_CHANGED = "DURATION_TYPE_CHANGED"
export const DURATION_VALUE_CHANGED = "DURATION_VALUE_CHANGED"
export const ON_PROJECT_FORM_FIELD_CHANGE = "ON_PROJECT_FORM_FIELD_CHANGE"
export const SELECTED_SKILL_TOGGLE = "SELECTED_SKILL_TOGGLE"
export const CHECK_PROJECT_VALIDATION = "CHECK_PROJECT_VALIDATION"
export const NEW_PROJECT_IMAGE_UPLOADED = "NEW_PROJECT_IMAGE_UPLOADED"
export const NEW_PROJECT_IMAGE_REMOVED = "NEW_PROJECT_IMAGE_REMOVED"


