Object.defineProperty(exports, "__esModule", {
  value: true
});
var FETCHING = exports.FETCHING = "FETCHING";

var GET_PROJECTS_WITH_SKILLS = exports.GET_PROJECTS_WITH_SKILLS = "GET_PROJECTS_WITH_SKILLS";
var GET_PROJECTS_WITH_SKILLS_FAILED = exports.GET_PROJECTS_WITH_SKILLS_FAILED = "GET_PROJECTS_WITH_SKILLS_FAILED";
var GET_PROJECTS_WITH_SKILLS_FULFILLED = exports.GET_PROJECTS_WITH_SKILLS_FULFILLED = "GET_PROJECTS_WITH_SKILLS_FULFILLED";

var NEW_PROJECT = exports.NEW_PROJECT = "NEW_PROJECT";

var GET_TAGS = exports.GET_TAGS = "GET_TAGS";
var GET_TAGS_FULFILLED = exports.GET_TAGS_FULFILLED = "GET_TAGS_FULFILLED";
var GET_TAGS_FAILED = exports.GET_TAGS_FAILED = "GET_TAGS_FAILED";

var TAG_SELECTED = exports.TAG_SELECTED = "TAG_SELECTED";
var TAG_DISELECT = exports.TAG_DISELECT = "TAG_DISELECT";
var TAG_REMOVE = exports.TAG_REMOVE = "TAG_REMOVE";

var GET_SUGGESTED_SHOWCASES = exports.GET_SUGGESTED_SHOWCASES = "GET_SUGGESTED_SHOWCASES";
var GET_SUGGESTED_SHOWCASES_FULFILLED = exports.GET_SUGGESTED_SHOWCASES_FULFILLED = "GET_SUGGESTED_SHOWCASES_FULFILLED";

var SUGGESTED_IMAGE_CHOOSED = exports.SUGGESTED_IMAGE_CHOOSED = "SUGGESTED_IMAGE_CHOOSED";

var GET_SKILL_CATEGORIES = exports.GET_SKILL_CATEGORIES = "GET_SKILL_CATEGORIES";
var GET_SKILL_CATEGORIES_FAILED = exports.GET_SKILL_CATEGORIES_FAILED = "GET_SKILL_CATEGORIES_FAILED";
var GET_SKILL_CATEGORIES_FULFILLED = exports.GET_SKILL_CATEGORIES_FULFILLED = "GET_SKILL_CATEGORIES_FULFILLED";

var SET_SELECTED_PROJECT = exports.SET_SELECTED_PROJECT = "SET_SELECTED_PROJECT";

var SAVE_PROJECT = exports.SAVE_PROJECT = 'SAVE_PROJECT';
var SAVE_PROJECT_FAILED = exports.SAVE_PROJECT_FAILED = 'SAVE_PROJECT_FAILED';
var SAVE_PROJECT_FULFILLED = exports.SAVE_PROJECT_FULFILLED = 'SAVE_PROJECT_FULFILLED';

var PRICE_BUNDLE_CHANGED = exports.PRICE_BUNDLE_CHANGED = "PRICE_BUNDLE_CHANGED";
var DURATION_TYPE_CHANGED = exports.DURATION_TYPE_CHANGED = "DURATION_TYPE_CHANGED";
var DURATION_VALUE_CHANGED = exports.DURATION_VALUE_CHANGED = "DURATION_VALUE_CHANGED";
var ON_PROJECT_FORM_FIELD_CHANGE = exports.ON_PROJECT_FORM_FIELD_CHANGE = "ON_PROJECT_FORM_FIELD_CHANGE";
var SELECTED_SKILL_TOGGLE = exports.SELECTED_SKILL_TOGGLE = "SELECTED_SKILL_TOGGLE";
var CHECK_PROJECT_VALIDATION = exports.CHECK_PROJECT_VALIDATION = "CHECK_PROJECT_VALIDATION";
var NEW_PROJECT_IMAGE_UPLOADED = exports.NEW_PROJECT_IMAGE_UPLOADED = "NEW_PROJECT_IMAGE_UPLOADED";
var NEW_PROJECT_IMAGE_REMOVED = exports.NEW_PROJECT_IMAGE_REMOVED = "NEW_PROJECT_IMAGE_REMOVED";