Object.defineProperty(exports,"__esModule",{value:true});var SESSION_TOKEN_REQUEST=exports.SESSION_TOKEN_REQUEST="SESSION_TOKEN_REQUEST";
var SESSION_TOKEN_SUCCESS=exports.SESSION_TOKEN_SUCCESS="SESSION_TOKEN_SUCCESS";
var SESSION_TOKEN_FAILURE=exports.SESSION_TOKEN_FAILURE="SESSION_TOKEN_FAILURE";
var DELETE_TOKEN_REQUEST=exports.DELETE_TOKEN_REQUEST="DELETE_TOKEN_REQUEST";
var DELETE_TOKEN_SUCCESS=exports.DELETE_TOKEN_SUCCESS="DELETE_TOKEN_SUCCESS";
var LOGOUT=exports.LOGOUT="LOGOUT";
var REGISTER=exports.REGISTER="REGISTER";
var LOGIN=exports.LOGIN="LOGIN";
var FORGOT_PASSWORD=exports.FORGOT_PASSWORD="FORGOT_PASSWORD";

var LOGOUT_REQUEST=exports.LOGOUT_REQUEST="LOGOUT_REQUEST";
var LOGOUT_SUCCESS=exports.LOGOUT_SUCCESS="LOGOUT_SUCCESS";

var LOGOUT_FAILURE=exports.LOGOUT_FAILURE="LOGOUT_FAILURE";
var LOGIN_REQUEST=exports.LOGIN_REQUEST="LOGIN_REQUEST";
var LOGIN_SUCCESS=exports.LOGIN_SUCCESS="LOGIN_SUCCESS";
var LOGIN_FAILURE=exports.LOGIN_FAILURE="LOGIN_FAILURE";
var ON_AUTH_FORM_FIELD_CHANGE=exports.ON_AUTH_FORM_FIELD_CHANGE="ON_AUTH_FORM_FIELD_CHANGE";
var SIGNUP_REQUEST=exports.SIGNUP_REQUEST="SIGNUP_REQUEST";
var SIGNUP_SUCCESS=exports.SIGNUP_SUCCESS="SIGNUP_SUCCESS";
var SIGNUP_FAILURE=exports.SIGNUP_FAILURE="SIGNUP_FAILURE";
var RESET_PASSWORD_REQUEST=exports.RESET_PASSWORD_REQUEST="RESET_PASSWORD_REQUEST";
var RESET_PASSWORD_SUCCESS=exports.RESET_PASSWORD_SUCCESS="RESET_PASSWORD_SUCCESS";
var RESET_PASSWORD_FAILURE=exports.RESET_PASSWORD_FAILURE="RESET_PASSWORD_FAILURE";