export const FETCHING = "FETCHING"
export const GET_PORTFOLIO = "GET_MY_PORTFOLIO"
export const GET_PORTFOLIO_FULFILLED = "GET_PORTFOLIO_FULFILLED"
export const GET_PORTFOLIO_ERROR = "GET_PORTFOLIO_ERROR"
export const SHOWCASE_SEARCHVALUE_CHANGED = "SHOWCASE_SEARCHVALUE_CHANGED"
export const SHOWCASE_SEARCHVALUE_CLEAR = "SHOWCASE_SEARCHVALUE_CLEAR"

export const GET_TAG_AUTOCOMPLETE = "GET_TAG_AUTOCOMPLETE"
export const GET_TAG_AUTOCOMPLETE_FULFILLED = "GET_TAG_AUTOCOMPLETE_FULFILLED"
export const GET_SHOWCASE_SUGGESTED_TAGS = "GET_SHOWCASE_SUGGESTED_TAGS"
export const GET_SHOWCASE_SUGGESTED_TAGS_FULFILLED = "GET_SHOWCASE_SUGGESTED_TAGS_FULFILLED"

export const SET_TAG_AUTOCOMPLETE = "SET_TAG_AUTOCOMPLETE"
export const SET_TAG_AUTOCOMPLETE_FULFILLED = "SET_TAG_AUTOCOMPLETE_FULFILLED"